"""groups table

Revision ID: 3172afd782cb
Revises: 8c697c377cc6
Create Date: 2019-05-05 11:25:09.385052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3172afd782cb'
down_revision = '8c697c377cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('picture', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_group_picture'), 'group', ['picture'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_picture'), table_name='group')
    op.drop_column('group', 'picture')
    # ### end Alembic commands ###
