"""events table

Revision ID: 7962b1a9db28
Revises: 3349ca3630ad
Create Date: 2019-05-04 19:29:55.856855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7962b1a9db28'
down_revision = '3349ca3630ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('eventId')
    )
    op.create_index(op.f('ix_event_location'), 'event', ['location'], unique=False)
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
    op.create_index(op.f('ix_event_time'), 'event', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_time'), table_name='event')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_location'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
